In [1]:
#输出一个字符串
print("Hello World!")

Hello World!


In [2]:
#实现大数计算
123456789123456789 * 123456789123456789

15241578780673678515622620750190521

In [3]:
#+号实现字符串相连
print("Hello "+"World!")

Hello World!


In [4]:
#*实现字符串的复制
print("Hello World!"*3)

Hello World!Hello World!Hello World!


In [10]:
str = r'c:\now'
str

'c:\\now'

In [15]:
list(range(1,0))

[]

In [32]:
a = [1,2,3,4,5]
print(a[-1])

5
[1, 2, 3, 4, 5]


In [88]:
a = [1, 2, 3]
b = [4, 5, 6]
c = [4, 5, 6, 7, 8]
zipped_1 = zip(a,b)
zip_1 = zip(*zipped_1)
print(*zip_1)

(1, 2, 3) (4, 5, 6)


In [137]:
temp = filter(lambda x: x % 2 ,range(10))
print(list(temp))
list(map(lambda x: x * 2 ,range(10)))

[1, 3, 5, 7, 9]


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [ ]:
def fibonacci(n):
    if n < 0:
        return -1
    if n == 0:
        return 0
    if n == 1 or n == 2:
        return 1
    else:
        return fibonacci(n - 1) + fibonacci(n - 2)


In [39]:
a = {1, 4, 4, 3, 3, 6, 2, 2}
for x in a:
    print(x, end = ' ')
print('')
print(0 in a)
a.add(10)
a.remove(4)

print(a)

1 2 3 4 6 
False
{1, 2, 3, 6, 10}


In [46]:
try:
    sum = 1 + '1'
    with open('1.txt') as f:
    print(f.read())
    f.close()
except (OSError, TypeError) as reason:
    print('出错原因' + str(reason))

出错原因unsupported operand type(s) for +: 'int' and 'str'


In [47]:
try:
    a = input("输入一个数：")
    #判断用户输入的是否为数字
    if(not a.isdigit()):
        raise ValueError("a 必须是数字")
except ValueError as reason:
    print("出错原因",str(reason))

输入一个数：s
出错原因 a 必须是数字


当前的位置: 7 0


In [75]:
class Ball:
    def __init__(self, name):
        self.name = name
    def fun(self):
        print("%s" % self.name)
a = Ball("篮球")
a.fun()

篮球


In [25]:
class MyProperty:
    def __init__(self, fget = None, fset = None, fdel = None):
        self.fget = fget
        self.fset = fset
        self.fdel = fdel
    def __get__(self, instance, owner):
        return self.fget(instance)
    def __set__(self, instance, value):
        self.fset(instance, value)
    def __delete__(self, instance):
        self.fdel(instance)

class C:
    def __init__(self):
        self._x = None
    def getX(self):
        return self._x
    def setX(self, value):
        self._x = value
    def delX(self):
        del self._x
    x = MyProperty(getX, setX, delX)

c.x = 'Hello'
print(c.x)




Hello


In [27]:
class Celsius:
    def __init__(self, value = 26.0):
        self.value = float(value)
    def __get__(self, instance, owner):
        return self.value
    def __set__(self, instance, value):
        self.value = float(value)

class Fahrenheit:
    def __get__(self, instance, owner): 
        return instance.cel * 1.8 + 32
    def __set__(self, instance, value):
        instance.cel = (float(value) - 32)/1.8
        
class Temperature:
    cel = Celsius()
    fah = Fahrenheit()


78.80000000000001

In [37]:
#编写一个不可改变的自定义列表，记录每个元素列表中元素的访问次数
class myList:
    def __init__(self, *args):
        self.values = [x for x in args]
        self.count = {}.fromkeys(range(len(self.values)), 0)
    def __len__(self):
        return len(self.values)
    def __getitem__(self, key):
        self.count[key] += 1
        return self.values[key]

L1 = myList(1,3,5,7,9)
L2 = myList(2,4,6,8,10)
print(L1[1])
print(L1[1] + L2[2])
print(L1.count)
print(L2.count)


3
9
{0: 0, 1: 2, 2: 0, 3: 0, 4: 0}
{0: 0, 1: 0, 2: 1, 3: 0, 4: 0}


In [1]:
class Fibs:
    def __init__(self,n = 10):
        self.a = 0
        self.b = 1
        self.n = n
    def __iter__(self):
        return self
    def __next__(self):
        self.a,self.b = self.b, self.a + self.b
        if self.a > self.n:
            raise StopIteration
        return self.a

f = Fibs(10)

for each in f:
    print(each)

1
1
2
3
5
8


In [41]:
import numpy as np

d = np.arange(0,  20, 2)
print(d.shape)

e = d.reshape(-1, 5)
print(e.shape)

f = d.reshape(2, -1)
print(f.shape)


(10,)
(2, 5)
(2, 5)


In [64]:
import numpy as np

arr1  = np.array([1, 1, 4, 5, 5, 5, 7, 6, 8, 3, 2, 1, 8])
np.unique(arr1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [85]:
a = np.arange(0, 12, 0.5).reshape(4, -1)
#默认按照'%.18e'格式保存数值，以空格分隔
np.savetxt("a.txt", a)
print(np.loadtxt("a.txt"))
#保存为整数，以逗号分隔
np.savetxt("a.txt", a, fmt="%d" ,delimiter=",")
print(np.loadtxt("a.txt", delimiter=","))


[[ 0.   0.5  1.   1.5  2.   2.5]
 [ 3.   3.5  4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5  8.   8.5]
 [ 9.   9.5 10.  10.5 11.  11.5]]
[[ 0.  0.  1.  1.  2.  2.]
 [ 3.  3.  4.  4.  5.  5.]
 [ 6.  6.  7.  7.  8.  8.]
 [ 9.  9. 10. 10. 11. 11.]]


In [108]:
import numpy as np
with open("test.csv",encoding = 'utf-8') as f:
    npData = np.loadtxt(f,str,delimiter = ",") 
    #usecols读取指定列
    #skiprows = n 跳过前n行
    print(npData)

[['姓名' '年龄' '体重' '身高']
 ['张三' '30' '75' '165']
 ['李四' '45' '60' '170']
 ['王五' '15' '30' '120']]


In [119]:
import numpy as np
import os

a = np.arange(8)
b = np.add.accumulate(a)
c = a + b
f = open("result.npz", "wb")
np.save(f, a)
np.save(f, b)
np.save(f, c)
f.close()
f = open("result.npz", "rb")
print(np.load(f))
print(np.load(f))
print(np.load(f))

[0 1 2 3 4 5 6 7]
[ 0  1  3  6 10 15 21 28]
[ 0  2  5  9 14 20 27 35]
